"""The plan.json contract — one owner for the schema and the segments.ts emitter.

Previously the segments.ts serialiser was duplicated in plan_creative.py and
tighten_gaps.py, and tighten's copy emitted a header crediting plan_creative.
Both now call write_segments_ts() here.

plan.json is a PURE function of (config_core, clip probes). It carries no
accumulated edit history: manual + auto cuts live in edits.json so that
re-planning can never destroy them.
"""
import json
import os

from hashing import atomic_write_json, atomic_write_text, h_json

PLAN_SCHEMA = 2

HEADER = "// Auto-generated by caption-ugc — do not edit by hand.\n"


def seg_recipe(plan, seg):
    """Canonical identity of a segment's *content*, excluding its key name.

    Excluding the key is what makes renaming segments (H1 -> H_C1H1) free: the
    rendered artifact is identical, so no rebuild is triggered by a rename.
    """
    s = plan["segments"][seg]
    return h_json({
        "clips": [[c["src"], c["trimBefore"], c["trimAfter"]] for c in s["clips"]],
        "fps": plan["fps"], "w": plan["width"], "h": plan["height"],
    })


def segment_spans(plan, seg):
    """[(seg_start_frame, seg_end_frame, clip_index, src, trimBefore, trimAfter)]"""
    spans, acc = [], 0
    for i, c in enumerate(plan["segments"][seg]["clips"]):
        n = c["trimAfter"] - c["trimBefore"]
        spans.append((acc, acc + n, i, c["src"], c["trimBefore"], c["trimAfter"]))
        acc += n
    return spans


def total_frames(clips):
    return sum(c["trimAfter"] - c["trimBefore"] for c in clips)


def write_segments_ts(plan, path):
    seg_ts = [{"key": k, "totalFrames": v["totalFrames"], "clips": v["clips"]}
              for k, v in plan["segments"].items()]
    meta = {"fps": plan["fps"], "width": plan["width"], "height": plan["height"]}
    atomic_write_text(path, HEADER
                      + "export const META = %s;\n" % json.dumps(meta)
                      + "export const SEGMENTS = %s as const;\n" % json.dumps(seg_ts, indent=1))


def write_plan(plan, path):
    atomic_write_json(path, plan)


def load_plan(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def validate_plan(plan):
    """Fail loudly on schema drift rather than KeyError-ing three scripts later."""
    errs = []
    for k in ("schema", "folder", "fps", "width", "height", "segments", "combos",
              "multiCta", "cropTo4x5", "sources", "config"):
        if k not in plan:
            errs.append("missing top-level key: %s" % k)
    if errs:
        return errs
    if plan["schema"] != PLAN_SCHEMA:
        errs.append("plan schema %r != expected %r (re-plan required)"
                    % (plan["schema"], PLAN_SCHEMA))
    for key, s in plan["segments"].items():
        if not s.get("clips"):
            errs.append("segment %s has no clips" % key)
            continue
        for c in s["clips"]:
            for f in ("src", "trimBefore", "trimAfter"):
                if f not in c:
                    errs.append("segment %s clip missing %s" % (key, f))
            if c.get("trimAfter", 0) <= c.get("trimBefore", 0):
                errs.append("segment %s clip %s has empty range %s..%s"
                            % (key, c.get("src"), c.get("trimBefore"), c.get("trimAfter")))
        if s.get("totalFrames") != total_frames(s["clips"]):
            errs.append("segment %s totalFrames %s != sum(clips) %s"
                        % (key, s.get("totalFrames"), total_frames(s["clips"])))
    for c in plan["combos"]:
        for sk in c["segments"]:
            if sk not in plan["segments"]:
                errs.append("combo %s references unknown segment %s" % (c["key"], sk))
        want = sum(plan["segments"][s]["totalFrames"] for s in c["segments"]
                   if s in plan["segments"])
        if c.get("totalFrames") != want:
            errs.append("combo %s totalFrames %s != %s" % (c["key"], c.get("totalFrames"), want))
    return errs
