#!/usr/bin/env python3
r"""One-command entry point: scaffold a project if needed, then hand off to build.py.

    python3 run_creative.py config.json [--skip-scaffold] [build.py flags...]

WHAT CHANGED AND WHY: this script used to run the whole pipeline itself, and it
could not complete. Step 7 discovered segment keys with

    node -e 'require("./src/segments").SEGMENTS.forEach(s=>console.log(s.key))'

which cannot work — src/segments.ts is TypeScript with ESM exports and Node's CJS
resolver will not resolve it (MODULE_NOT_FOUND, verified). It died after captioning,
before rendering anything. The keys were always available in plan.json.

It also rebuilt everything unconditionally: step 3 rebuilt every segment WAV, which
bumped every mtime, which made step 4 delete every transcription cache, which forced
a full large-v3 + Gemini re-run on every invocation. Fast iteration was impossible
by construction. build.py is content-hash incremental instead.
"""
import argparse
import json
import os
import subprocess
import sys

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(SCRIPTS)
TEMPLATE = os.path.join(SKILL, "template", "src")


def sh(cmd, cwd=None, shell=False):
    print("· " + (cmd if shell else " ".join(cmd)))
    subprocess.run(cmd, cwd=cwd, shell=shell, check=True)


def scaffold(proj, folder, ext, clips):
    fresh = not os.path.exists(os.path.join(proj, "package.json"))
    if fresh:
        parent = os.path.dirname(proj) or "."
        os.makedirs(parent, exist_ok=True)
        sh("npx create-video@latest --yes --blank --no-tailwind %s"
           % json.dumps(os.path.basename(proj)), cwd=parent, shell=True)
        sh("npm i", cwd=proj, shell=True)
        remv = subprocess.check_output(
            ["node", "-p", "require('./node_modules/remotion/package.json').version"],
            cwd=proj).decode().strip()
        sh("npm i @remotion/captions@%s @remotion/google-fonts@%s" % (remv, remv),
           cwd=proj, shell=True)

    os.makedirs(os.path.join(proj, "src"), exist_ok=True)
    os.makedirs(os.path.join(proj, "public"), exist_ok=True)
    # Only copy templates into a FRESH project, or when they are missing. The old
    # version overwrote them on every run, silently reverting any local tweak to
    # caption-style.ts.
    for f in ("Composition.tsx", "caption-style.ts", "Root.tsx"):
        dst = os.path.join(proj, "src", f)
        if fresh or not os.path.exists(dst):
            sh(["cp", os.path.join(TEMPLATE, f), dst])
    idx = os.path.join(proj, "src", "index.css")
    if not os.path.exists(idx):
        with open(idx, "w", encoding="utf-8") as fh:
            fh.write("/* blank */\n")
    srts = os.path.join(proj, "src", "srts.ts")
    if not os.path.exists(srts):
        with open(srts, "w", encoding="utf-8") as fh:
            fh.write("// placeholder — regenerated by build.py\n"
                     "export const SEG_SRTS: Record<string, string> = {};\n")

    for c in clips:
        src = os.path.join(folder, c + ext)
        dst = os.path.join(proj, "public", c + ext)
        if not os.path.exists(src):
            sys.exit("missing clip: %s" % src)
        if os.path.exists(dst):
            os.remove(dst)
        try:
            os.link(src, dst)
        except OSError as e:
            sys.exit("could not hardlink %s -> %s (%s). Clips and the project must "
                     "be on the same filesystem." % (src, dst, e))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("config")
    ap.add_argument("--skip-scaffold", action="store_true")
    a, rest = ap.parse_known_args()

    with open(a.config, encoding="utf-8") as fh:
        cfg = json.load(fh)
    folder = cfg["folder"]
    ext = cfg.get("ext", ".mov")
    proj = cfg.get("proj") or os.path.join(folder, "_edit")

    sys.path.insert(0, SCRIPTS)
    from buildgraph import unique_clips
    clips = unique_clips(cfg)

    if not a.skip_scaffold:
        scaffold(proj, folder, ext, clips)

    cmd = [sys.executable, os.path.join(SCRIPTS, "build.py"), proj,
           "--config", os.path.abspath(a.config)] + rest
    print("· " + " ".join(cmd))
    return subprocess.run(cmd).returncode


if __name__ == "__main__":
    sys.exit(main())
