r"""SRT -> ASS, reproducing template/src/caption-style.ts exactly.

Non-obvious decisions, all empirically verified on this machine (see DEVNOTES):
  Fontsize      = css_px * (usWinAsc+usWinDesc)/upm   (libass follows VSFilter's
                  CELL-height convention, so 62px CSS is NOT Fontsize 62)
  Outline       = css_stroke/2  (CSS WebkitTextStroke is centre-aligned and
                  paintOrder:"stroke fill" repaints the inner half)
  YCbCr Matrix  = None  (otherwise libass pre-mangles RGB for VSFilter compat and
                  pure white arrives at luma ~235 instead of 255)
  PlayResX/Y    = the real frame size (libass scales by frame_h/PlayResY)
  WrapStyle     = 2  (never let libass re-wrap; the captioner's line breaks ARE
                  the layout, and \pos disables the margins that would constrain it)
  ONE EVENT PER VISUAL LINE with \an5\pos: ASS's line advance is Fontsize (~75px)
                  but CSS lineHeight is 1.1*62 = 68.2px, so a multi-line \N event
                  would be ~7px too tall. Positioning each line explicitly is exact.
"""
import os
import re
import subprocess
import sys

import caption_spec as spec
from srt import parse_srt

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPTS)
import portable                                              # noqa: E402

# NOTE: this backend BURNS captions, so it needs an ffmpeg built with libass —
# not every build has it. Only the `ass` caption backend comes through here;
# Mariposa Studio's Clip Cutter uses the CapCut hand-off, which burns nothing
# and so has no libass requirement.
FFMPEG = portable.ffmpeg() or "ffmpeg"

FONTSELECT = re.compile(
    r"fontselect:\s*\(([^,]+),\s*(\d+),\s*(\d+)\)\s*->\s*(.+?),\s*(-?\d+),\s*(\S+)\s*$")


def esc_filter_path(p):
    """Escape a path for use as an ffmpeg filter option value."""
    return p.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace(",", "\\,")


def ms_to_ass(ms, fps):
    """Frame-exact ASS timestamp.

    ASS has centisecond resolution but one frame at 30fps is 3.33cs, so naive
    rounding can shift a cue by a frame relative to the old Remotion output.
    Pick the centisecond that floors into the same frame Remotion would use.
    """
    f = int(round(ms * fps / 1000.0))
    cs = (f * 100) // fps
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, c = divmod(rem, 100)
    return "%d:%02d:%02d.%02d" % (h, m, s, c)


def line_y(i, n, fontspec):
    """Vertical centre of visual line i of n, matching CSS block-centring at 55%."""
    corr = fontspec.baseline_correction(spec.FONT_PX) if fontspec else 0.0
    return round(spec.TOP_FRAC * spec.HEIGHT
                 + (i - (n - 1) / 2.0) * spec.FONT_PX * spec.LINE_HEIGHT
                 + corr, 1)


def measure_line(text, fontspec):
    """Advance width in px from hmtx. No GPOS kerning, so it over-estimates
    slightly — conservative for a safe-margin check, which is what we want."""
    if fontspec is None:
        return 0.0
    try:
        from fontTools.ttLib import TTFont
    except ImportError:
        return 0.0
    global _CMAP_CACHE
    key = fontspec.path
    if key not in _CMAP_CACHE:
        f = TTFont(fontspec.path, lazy=True)
        cmap = f.getBestCmap()
        hmtx = f["hmtx"].metrics
        _CMAP_CACHE[key] = (cmap, hmtx, fontspec.upm)
        f.close()
    cmap, hmtx, upm = _CMAP_CACHE[key]
    total = 0
    for ch in text:
        gn = cmap.get(ord(ch))
        if gn is None:
            gn = cmap.get(ord(" "))
        if gn and gn in hmtx:
            total += hmtx[gn][0]
    return total * spec.FONT_PX / float(upm)


_CMAP_CACHE = {}


def ass_alpha(opacity):
    """ASS AA byte is TRANSPARENCY, so 45% opaque -> 0x8C."""
    return int(round((1.0 - opacity) * 255))


def build_ass(cues, fps, total_frames, fontspec, provenance=None):
    """-> (ass_text, warnings). Warnings are returned, never printed or swallowed."""
    warn = []
    fontsize = fontspec.ass_fontsize(spec.FONT_PX) if fontspec else spec.FONT_PX
    fontname = fontspec.family if fontspec else "Inter"
    back = "&H%02X000000" % ass_alpha(spec.SHADOW_ALPHA)
    seg_end_ms = total_frames * 1000.0 / fps

    head = ["[Script Info]", "; Generated by caption-ugc srt2ass — do not edit by hand."]
    for k, v in sorted((provenance or {}).items()):
        head.append("; %s=%s" % (k, v))
    head += [
        "ScriptType: v4.00+",
        "PlayResX: %d" % spec.WIDTH,
        "PlayResY: %d" % spec.HEIGHT,
        "ScaledBorderAndShadow: yes",
        "WrapStyle: 2",
        "YCbCr Matrix: None",
        "Collisions: Normal",
        "",
        "[V4+ Styles]",
        ("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
         "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
         "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"),
        ("Style: Cap,%s,%s,&H00FFFFFF,&H00FFFFFF,&H00000000,%s,0,0,0,0,100,100,0,0,1,"
         "%s,%s,5,%d,%d,0,1" % (fontname, fontsize, back, spec.OUTLINE,
                                spec.SHADOW_PX, spec.PAD_X, spec.PAD_X)),
        "",
        "[Events]",
        ("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"),
    ]

    events = []
    for ci, c in enumerate(cues, 1):
        if c["end"] <= c["start"]:
            warn.append("INV cue %d: end<=start (dropped)" % ci)
            continue
        end = c["end"]
        if end > seg_end_ms + 200:
            warn.append("OOB cue %d: ends %.2fs past segment end (clamped)"
                        % (ci, (end - seg_end_ms) / 1000.0))
            end = seg_end_ms
        lines = [ln for ln in c["text"].split("\n") if ln.strip()]
        if not lines:
            continue
        if len(lines) > spec.MAX_LINES:
            warn.append("L%d cue %d: %d lines exceeds SOP max %d"
                        % (len(lines), ci, len(lines), spec.MAX_LINES))
        n = len(lines)
        for i, ln in enumerate(lines):
            w = measure_line(ln, fontspec)
            if w > spec.SAFE_W:
                warn.append("WIDE cue %d line %d: %.0fpx > %dpx safe width — %r"
                            % (ci, i + 1, w, spec.SAFE_W, ln))
            events.append("Dialogue: 0,%s,%s,Cap,c%dL%d,0,0,0,,{\\an5\\pos(%d,%s)}%s"
                          % (ms_to_ass(c["start"], fps), ms_to_ass(end, fps), ci, i + 1,
                             spec.WIDTH // 2, line_y(i, n, fontspec), ln))
    return "\n".join(head + events) + "\n", warn


def srt_file_to_ass(srt_path, fps, total_frames, fontspec, provenance=None):
    with open(srt_path, encoding="utf-8") as fh:
        cues, bad = parse_srt(fh.read())
    text, warn = build_ass(cues, fps, total_frames, fontspec, provenance)
    for b in bad:
        warn.append("UNPARSED srt block: %r" % b[:60])
    return text, warn, len(cues)


def verify_font(ass_path, fontsdir, expect_ttf, expect_postscript, probe_video, at_sec):
    """Render ONE frame and assert libass resolved ONLY our font.

    This is mandatory before any burn: a font fallback is indistinguishable from
    success (exit 0, no warning) unless you parse libass's verbose log.
    """
    p = subprocess.run(
        [FFMPEG, "-hide_banner", "-v", "verbose", "-ss", "%.3f" % at_sec,
         "-i", probe_video, "-frames:v", "1",
         "-vf", "ass=%s:fontsdir=%s" % (esc_filter_path(ass_path), esc_filter_path(fontsdir)),
         "-f", "null", "-"],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    err = p.stderr.decode("utf-8", "replace")
    hits = [m for m in (FONTSELECT.search(l) for l in err.splitlines()) if m]
    if not hits:
        raise RuntimeError(
            "libass selected no font — no cue visible at t=%.3fs in %s. Pick a "
            "timestamp inside a cue." % (at_sec, os.path.basename(probe_video)))
    want = os.path.realpath(expect_ttf)
    for m in hits:
        fam, _w, _i, path, _idx, ps = m.groups()
        if os.path.realpath(path.strip()) != want:
            raise RuntimeError(
                "FONT FALLBACK: libass resolved %r to %s (%s), expected %s. "
                "Captions would ship in the wrong typeface."
                % (fam, path.strip(), ps.strip(), want))
        if expect_postscript and ps.strip() != expect_postscript:
            raise RuntimeError("FONT FACE MISMATCH: got postscript %s, expected %s"
                               % (ps.strip(), expect_postscript))
    for l in err.splitlines():
        if "Glyph 0x" in l and "not found" in l:
            raise RuntimeError("MISSING GLYPH (libass substituted per-character): " + l.strip())
    return len(hits)
